name: Spell checking
on:
  push:

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: jsoref/check-spelling@prerelease
      with:
        config: .github/actions/spell-check
        debug: 1
